# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Lint yaml files
on: push
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.value }}
    steps:
      - name: Fetch main branch
        uses: actions/checkout@v4
        with:
          ref: main
      - name: Fetch working branch
        uses: actions/checkout@v4
      - name: Get changed files
        id: matrix
        run: echo value="$(git diff origin/main HEAD --name-only | jq -R -s -c 'split("\n") | .[:-1]')" >> "$GITHUB_OUTPUT"
      - name: Print changed files
        run: echo "${{ steps.matrix.outputs.value }}"
  lint:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      - name: Fetch working branch
        uses: actions/checkout@v4
      - name: Install yamllint
        run: pip install yamllint
      - name: Lint YAML files in "${{ matrix.value }}"
        id: lint
        run: yamllint -c .github/workflows/yamllint/rules.yaml --no-warnings --format github ${{ matrix.value }}
      - name: Lint step has failed
        if: ${{ failure() && steps.lint.conclusion == 'failure' }}
        run: echo Lint failed -- See https://yamllint.readthedocs.io/en/stable/rules.html for lint rules.
